name: Hello world custom private action
author: Dusan Mijatovic
description: Hello world demo action from docker action
inputs:
  who-to-greet:
    description: Provide info who to greet with hello
    required: true
    default: Dusan
outputs:
  time:
    description: Logs the time of greeting
runs:
  # only 2 options: node12 or docker
  using: docker
  # can be docker image docker://node:16-apline
  # or Dockerfile
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}