name: Context list

on:
  workflow_dispatch:
  push:
  pull_request:
  issues:

jobs:
  contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Log job context
        run: echo '${{ toJSON(job) }}'
      - name: Log steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Log runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Log strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Log matrix context
        run: echo '${{ toJSON(matrix) }}'
  log_contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Log Github context
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"
      - name: Job context
        env:
          JOB_CONTEXT: ${{toJson(job)}}
        run: echo "$JOB_CONTEXT"
      - name: Steps context
        env:
          STEPS_CONTEXT: ${{toJson(steps)}}
        run: echo "$STEPS_CONTEXT"
      - name: Runner context
        env:
          RUNNER_CONTEXT: ${{toJson(runner)}}
        run: echo "$RUNNER_CONTEXT"
      - name: Secrets context
        env:
          SECRETS_CONTEXT: ${{toJson(secrets)}}
        run: echo "$SECRETS_CONTEXT"
