name: Docker containers

on:
  push:
    branches:
      - dev

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      - image: node:16-alpine
        env:
          ENVIRONMENT: production
    steps:
      - name: log version
        run: |
          node -v
          cat /etc/os-release