name: Docker containers

on:
  push:
    branches:
      - dev

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      - image: node:v16-alpine
        env:
          - ENV:'production'
    steps:
      - name: log version
        run: |
          node -v
          cat /etc/os-release