name: Function expressions

on:
  push:
    branches:
      - dev

jobs:
  functions:
    runs-on: ubuntu-latest
    env:
      USER: {{github.actor}}
    steps:
      - name: Print fn test
        run: |
          echo ${{ contains('hello','ll') }}
          echo ${{ startsWith('hello','hel')}}
          echo ${{ endsWith('hello','lo')}}
          echo ${{ format('Hello {0} {1}', $USER,"!!!") }}