name: Javascript action example

on:
  push:
    # run on push only to these branches
    branches:
      - dev

jobs:
  run-js-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS action
        id: greetAction
        uses: actions/hello-world-javascript-action@v1
        # provide parameters to be used by action
        with:
          who-to-greet: Dusan
      - name: Log greeting time
        # call out action output (in action documentation)
        # we use id to reffer to step by id
        run: echo "${{ steps.greetAction.outputs.time }}"