name: Manual custom action and push on dev branc

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  custom-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show files
        run: |
          cd .github/actions/hello
          ls -lha
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Custom Action For This Project"
      - name: Log action time
        run: |
          echo "Time: ${{steps.hello.outputs.time}}"