name: Test frontend on each push to dev branch

on:
  push:
    branches:
      - dev

jobs:
  test-vue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependecies
        run: npm ci
      - name: run unit tests
        run: npm run test:coverage