name: On push to dev branch run unit tests

on:
  push:
    branches:
      - dev

jobs:
  unit-tests-vue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          # create unique cache key to reload every time we change dependencies
          key: node-${{runner.os}}-${{hashFiles('**/package-lock-json')}}
          restore-key: node-${{runner.os}}-
      - name: install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependecies
        run: npm ci
      - name: run unit tests
        run: npm run test:coverage