name: On pull request to master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit-tests-vue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          # create unique cache key to reload every time we change dependencies
          key: node-v16-${{runner.os}}-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            node-v16-${{runner.os}}-
      - name: install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependecies
        run: npm ci
      - name: run unit tests
        run: npm run test:coverage
      - name: upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: code coverage
          path: coverage
          retention-days: 30
      - name: build package
        # only 2 == should be used
        if: github.event_name == 'push'
        run: npm run build
      - name: upload build folder
        # only on push to master
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: build package
          path: build
      - name: create a relase
        # only on push to master
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


  # build:
  #   runs-on: ubuntu-latest
  #   needs: ["test"]
  #   steps:
  #     - name: build frontend
  #       run: npm run build
