name: Release citation.cff file

on:
  release:
    types: [published]

jobs:
  citations:
   runs-on: ubuntu-latest

   steps:
    - name: checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@v3
      with:
        # checkout
        ref: ${{github.ref}}

    - name: get version tag
      run: |
        echo enviroment
        env
        echo tag $GITHUB_REF
        echo sha $GITHUB_SHA
        echo last tag in the repo
        git describe --abbrev=0
        echo repo status
        git status

    - name: update CITATION.cff with version and release date
      # use doublequotes in second replace "" to enable variable substitution with bash
      run: |
        echo replace version line
        sed -i -e "s/version:.*/version: $(git describe --abbrev=0)/" CITATION.cff
        echo replace date
        sed -i -e "s/date-released:.*/date-released: '$(date +%F)'/" CITATION.cff
        cat CITATION.cff

    # - name: commit changes
    #   run: |
    #     git add .
    #     git commit -m "release: update citation file"
    #     git push

    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "release: update citation file"
