name: Manual reuse workflows

on:
  workflow_dispatch:

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          # checkout complete history
          fetch-depth: 0

      - name: shell-env
        uses: ./.github/workflows/shell-env.yml@master
      - name: shell-on-push
        uses: ./.github/workflows/shell-on-push.yml@master