# more info about on schedule actions
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onschedule
name: Shell commands on schedule

on:
  push:
    branches:
      - never-run
  # schedule:
  #   # run schedule every 5 minute
  #   # check with crontab guru https://crontab.guru/#*/5_*_*_*_*
  #   - cron: "0/5 * * * *"

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print time
        run: date