name: Shell commands on pull request

on:
  pull_request:
    branches:
      - never-run


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo message
        run: echo "This is pull request"