name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        run: echo "Hello world!"
      - name: check node versions
        run: |
          node -v
          npm -v
      - name: display current working directory
        run: ls -lha
  run-python-command:
    runs-on: ubuntu-latest
    # depends on run shell command
    needs: ["run-shell-command"]
    steps:
      - name: run python command
        run: |
          import platform
          print (platform.processor())
        shell: python