name: Release all on tag push to master

on:
  push:
    branches:
      - master
    tags:
     - "v*"

jobs:
  release:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cache node_modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        # create unique cache key to reload every time we change dependencies
        key: node-v16-${{runner.os}}-${{hashFiles('**/package-lock.json')}}
        restore-keys: |
          node-v16-${{runner.os}}-
    - name: install Node v16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: install dependecies
      run: npm ci
    - name: run unit tests
      run: npm run test:coverage
    - name: automatic releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false

